### ISSUE TITLE
Future of repo + maintenance

### ISSUE THREAD

**Issue by MaerF0x0** [rlmcpherson/s3gof3r#141]
Hi there, I noticed there hasnt been an update in ~2.5 yrs. What is the plan/intention for maintenance of this repo?

**Comment by NickH-nz** [comment]
There's an official github fork that look much more recently maintained. We will be switching to that one.
https://github.com/github/s3gof3r

**Comment by snebel29** [comment]
It does feel just a fork to suit their own (Github) immediate needs, it does feel there is no desire to maintain the repository for the community over time.
