### ISSUE TITLE
memory leak?

### ISSUE THREAD

**Issue by hrez** [rlmcpherson/s3gof3r#33]
Hi,

Can something be done about memory consumption?
I've "gof3r put" with default options of what turned out to be 671Gb object.
It took 416m56.254s and gof3r memory utilization grew in the end to 21G virtual and 14G residential.

gof3r version 0.4.5

**Comment by rlmcpherson** [comment]
Closing, as memory usage was reduced the change to slices and other mitigations e.g. #62.

**Comment by roens** [comment]
Apologies for resurrecting this issue, but we've been experiencing memory issues with gof3r. We've had a daily backup running of a mysql db for some time, that has been slowly growing in size. The last successful backups are around 1.1TB. Recently it's been failing on S3's 10k part count limit, so I tried bumping up the initial `partsize` (first to 200MB then 400MB), and dropping the `concurrency` to just 2. It's' no longer hitting the part count limit, but now, `gof3r` is running out of memory. It's apparent now, watching memory usage that its ramp-up is less gradual. I've even tried adjusting mem/concurrency settings for `innobackupdex`, to no avail…

The actual command being used is:
```
innobackupex \
  --socket="/var/lib/mysql/mysql-${cluster_name}.sock" \
  --defaults-file="/etc/my-${cluster_name}.cnf" \
  --safe-slave-backup \
  --slave-info \
  --no-timestamp \
  --stream=xbstream \
  --compress \
  --compress-threads="${num_procs}" \
  --parallel=3 \
  --use-memory=500M \
  "${backup_dir}" | \
  gof3r put \
  -b "${bucket_name}" \
  -k "mysql/${cluster_name}/${backup_time}.xbstream" \
  --partsize=419430400 \
  --concurrency=1
```

The machine has 16GB, and baseline usage by other processes (mostly mysql) tends to use only about 42% of that. This machine is running CentOS 6.8. `gof3r version 0.5.0`
