### ISSUE TITLE
Support for AWS signature version 4

### ISSUE THREAD

**Issue by rlmcpherson** [rlmcpherson/s3gof3r#45]
All regions created after January 30, 2014 (e.g. Frankfurt) support only signature version 4. http://docs.aws.amazon.com/AmazonS3/latest/API/sig-v4-authenticating-requests.html

**Comment by schelhorn** [comment]
I'd also appreciate if this bug (which it is, in my view) would get fixed. s3gof3r is a very nice tool and a real alternative to all the other S3 utilities, but not being able to connect to the Frankfurt region is a dealbreaker for me. Obviously, Amayon will at some point turn off the older signatures anyway, so implementing AWS4-HMAC-SHA256 support would have value in its own right, in my opinion.

**Comment by ukd1** [comment]
@rlmcpherson is this planned anytime?

**Comment by trompx** [comment]
Same question here, I use Frankfurt buckets so I cannot go with s3gof3r for now..

**Comment by rlmcpherson** [comment]
@ukd1 Yes, pull requests are always welcome!

**Comment by cyberdelia** [comment]
#74 aims to fix this.

**Comment by rlmcpherson** [comment]
Fixed by #74. Thanks @cyberdelia!
