### ISSUE TITLE
Nil key request results in infinite select

### ISSUE THREAD

**Issue by mhoglan** [rlmcpherson/s3gof3r#57]
If a nil key, which results in string "", is requested an infinite select will occur since the workers will exit out because the `initChunks()` will have closed the `g.getCh` channel without putting anything on the channel.   

The for loop in `initChunks()` will not execute due to the negative content length

```
for i := int64(0); i < g.contentLen; {
...
}
```

Content length is set to -1 by golang if the HTTP response is deemed to be chunked transfer encoding or EOF close response.

When a nil key is requested, the resulting HTTP request is to the bucket URL only, which results in AWS returning a listing of the bucket which is a XML streamed response.   The streamed response will not contain any content-length header, and golang will set the content-length to -1 in the response.

Since to execute multipart GET requests, the content length is needed to be known, it can be assumed the client does not support working with chunked transfer encoded responses or EOF close responses, and all responses must contain a content-length.

Incoming pull request to address the issue.   Two guards put in place
* If content-length of response is -1, error
* If path requested is "" (nil for string), error

Feel like a similar fix can be added as discussed at the end of rlmcpherson/s3gof3r#55 that if the workers closed the channel when exiting or some notification that they have finished (maybe new channel?) then the `nextChunk()` would exit.

**Comment by rlmcpherson** [comment]
Fixed by #58.
