### ISSUE TITLE
AWS Key ID not existed in records

### ISSUE THREAD

**Issue by sayumeaw** [rlmcpherson/s3gof3r#65]
I got this message, "The AWS Access Key Id you provided does not exist in our records."
And what I typed was this, " ./gof3r put -b testbucket1 -k /root/gof3r_0.4.9_linux_amd64/bbb "

I was trying to put a file to a Japanese Object Storage Service which is compatible with S3 service.
I succeeded to put a file to it using S3 command. 
API key couldn't read correctly from environment variable.

Would you be kind to teach me how to fix this problem?
Where to change endpoint, access key, and secret key?
Also gof3r command is the same as go language?

**Comment by rlmcpherson** [comment]
If using the gof3r cli, you may specify keys via environment variables. Please see the Readme. 

This tool is designed for and tested against Amazon S3. Unfortunately, I can't troubleshoot problems with other S3-compatible services.
