### ISSUE TITLE
Behavior w.r.t. backpressure

### ISSUE THREAD

**Issue by uhoh-itsmaciek** [rlmcpherson/s3gof3r#66]
We've seen some situations where `gof3r` is using unexpectedly large amounts of memory (e.g., hundreds of megs of RSS). This seems odd, since there's nothing that's inherently memory-intensive in its functionality as I understand it. I thought the issue might be buffering: does gof3r provide backpressure when reading stdin is a lot faster than the S3 upload? Does it provide backpressure when writing to stdout is a lot slower than the S3 download?

**Comment by rlmcpherson** [comment]
Is this uploading or downloading? From your description it sounds like uploading. If it's occurring downloads, that could indicate an unknown memory leak. On uploads, gof3r tries to be smart (probably too smart) about doubling buffer sizes periodically to allow larger maximum upload size given the 10,000 part S3 limitation. 

With the current code, the best workaround is to increase initial part size and decrease concurrency to limit memory usage. The buffer size will only be increased if necessary. 

I'm open to a better solution.

The buffer size logic is here: https://github.com/rlmcpherson/s3gof3r/blob/ed07ab7f4c26c61b927fc5e51e80e2d3b40f4470/putter.go#L152

**Comment by rlmcpherson** [comment]
Related discussion in #33 as well.

**Comment by uhoh-itsmaciek** [comment]
You know, I think we might be using a version older than the fixes you'd put in there--I'm going to close this for now and reopen if I still see problems with a recent version. I'd looked at the docs, but hadn't looked at the closed issues Thanks!

**Comment by rlmcpherson** [comment]
Yeah, the memory usage was higher and less predictable before the switch to byte slices from bytes.Buffer so hopefully that will be sufficient.
