### ISSUE TITLE
nil pointer crash in 

### ISSUE THREAD

**Issue by bgdavidx** [rlmcpherson/s3gof3r#69]
Got this error after running for 5 days in production:

panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x4fac57]

goroutine 265104500 [running]:
github.com/rlmcpherson/s3gof3r.(*putter).Close(0xc21c8d9a20, 0x0, 0x0)
        /home/ec2-user/go/bin/src/github.com/rlmcpherson/s3gof3r/putter.go:255 +0xd17
main.func·006(0x0, 0x0, 0x0, 0x0)

Seems like S3 failure? The offending line of code is below:

https://github.com/rlmcpherson/s3gof3r/blob/master/putter.go#L255

defer checkClose(resp.Body, &err)

**Comment by rlmcpherson** [comment]
Thanks for opening this. Based on the stacktrace, it looks like `resp.Body` is nil. The standard net/http library guarantees that Body is always non-nil (http://golang.org/pkg/net/http/#Response) but are you perhaps using a non-standard http client? 

I'll add a nil check to the `checkClose` function to ensure this does not happen
