### ISSUE TITLE
gof3r dial tcp: i/o timeout on fedora 21

### ISSUE THREAD

**Issue by wts-dev** [rlmcpherson/s3gof3r#70]
When running gof3r on Fedora 21 (whether the 0.4.10 bin or the locally compiled 0.4.11) I receive a dial tcp: i/o timeout on both get and put. The same command with the same credentials works on CentOS 6 & 7. Below is a sample command:

    $ cat output | pv | gof3r put -b sqlbackup.wts.edu -k s3backup.test
This results in the following:

    18.6KiB 0:00:00 [5.99MiB/s] [    <=>                               ]
    gof3r error: Post https://s3.amazonaws.com/sqlbackup.wts.edu/s3backup.test?uploads: dial tcp: i/o timeout
A sample failed download looks as follows:

    gof3r error: Get https://s3.amazonaws.com/sqlbackup.wts.edu/nathan.wts.edu_backup_20150811035201.xbcrypt: dial tcp: i/o timeout                                                                                                              ]
I know that the credentials are not at fault, because the s3cmd works flawlessly with them. I also know that on the download, I am using the correct key. 

Any thoughts?

**Comment by rlmcpherson** [comment]
This might be occurring if the server is very bandwidth-constrained or if there are other network issues causing tcp timeouts. As a mitigation, you could try reducing the parallelism from the default of 10 to reduce network i/o contention. gof3r will retry failures like this but will fail after 10 attempts by default.

**Comment by rlmcpherson** [comment]
Closing. This is a network issue causing gof3r to run out of retries.
