### ISSUE TITLE
getter does not handle 200 OK

### ISSUE THREAD

**Issue by hashbrowncipher** [rlmcpherson/s3gof3r#75]
When the object being retrieved is small enough to fit in a single ranged request, Amazon S3 returns 200 OK. Since s3gof3r expects 206 Partial Content, it treats this response as a failure and retries the request.

**Comment by bgdavidx** [comment]
+1. I have the same issue:

2015/11/03 11:41:39 error on attempt 1: retrying chunk: 0, error: 200: ""
2015/11/03 11:41:39 error on attempt 2: retrying chunk: 0, error: 200: ""
2015/11/03 11:41:40 error on attempt 3: retrying chunk: 0, error: 200: ""
2015/11/03 11:41:40 error on attempt 4: retrying chunk: 0, error: 200: ""
2015/11/03 11:41:42 error on attempt 5: retrying chunk: 0, error: 200: ""
2015/11/03 11:41:46 error on attempt 6: retrying chunk: 0, error: 200: ""

**Comment by rlmcpherson** [comment]
This is a reasonable change but I am not able to replicate it in the US standard region. It may be a region-specific difference in S3 service. Where are you seeing this?

**Comment by bgdavidx** [comment]
@rlmcpherson it happens in us-west-2 with a 7kb file with a 20mb PartSize. It doesn't happen with a part size smaller than the file itself.

**Comment by rlmcpherson** [comment]
@bgdavidx Thanks. I still can't replicate it but it's likely a change to S3's behavior or a difference across regions. I'll merge the PR as 200 is an acceptable response in that scenario.
