### ISSUE TITLE
support for no credentials

### ISSUE THREAD

**Issue by WuTheFWasThat** [rlmcpherson/s3gof3r#78]
i can't use gof3r to get a public file, if i haven't provided any AWS keys

**Comment by rlmcpherson** [comment]
gof3r is built specifically for S3, so AWS keys and signing are built into the library. This isn't going to change. 

If you need to download from S3 without credentials any of the common tools, like curl, with http support will work. For a go tool, check out htcat: https://github.com/htcat/htcat

**Comment by WuTheFWasThat** [comment]
fair enough - thanks for the pointer to htcat
