### ISSUE TITLE
Golang 1.4 support

### ISSUE THREAD

**Issue by geofffranks** [rlmcpherson/s3gof3r#79]
Any chance this could be updated to work with golang 1.4? Currently having issues resulting from the URL.EscapedPath() function not existing.

**Comment by rlmcpherson** [comment]
The addition of EscapedPath fixes some issues that s3gof3r encountered with the url package in previous versions of go so I would prefer not to remove it. See https://golang.org/pkg/net/url/#URL 

I would accept a pull request that works around this issue, with tests demonstrating that url paths are escaped correctly.

**Comment by rlmcpherson** [comment]
Closing this as I'm not planning to support go versions earlier than 1.5. It should be possible to deploy a static binary in most cases so the go compiler version is not a production dependency.
