### ISSUE TITLE
AWS v2 signature compatibility

### ISSUE THREAD

**Issue by mbakke** [rlmcpherson/s3gof3r#80]
Some third-party S3 implementations (radosgw) do not support v4 yet. There should be an option to enable pre-0.5 signing method.

**Comment by rlmcpherson** [comment]
Are there S3 implementations other than radosgw with this issue? Is radosgw planning to add support? 

I would prefer not to support both signing methods for a couple reasons:
- code complexity and possible breaking api changes
- AWS V4 is supported in all regions and V2 signing has been deprecated for almost 2 years

For now, please use pre-0.5 versions. If there is sufficient demand for this, I may consider maintaining a separate branch with version 2 signing support.

**Comment by mbakke** [comment]
AWS4 support is [in progress](https://github.com/ceph/ceph/pull/4943). I understand your reasoning, as I went to imlement the changes and realized how intrusive it would be. Not aware of any other S3 implementations, and didn't know v2 had been deprecated *that* long.

Thanks for a superb client btw, Currently pushing 200MBps to an academic cloud service under construction. Leaving this open in case there are other users with the same problem, but I'm content with 0.4 for the time being.

**Comment by relvacode** [comment]
v2 support would be nice as a lot of on-premise S3-compatible stores (ECS, Ceph) only support V2 authentication.

**Comment by NoKriK** [comment]
Hi!

Basho Riak S2 (formerly Riak CS) only supports V2 as well.

**Comment by geofffranks** [comment]
Scality's ObjectAPI S3 product also is stuck at V2.

**Comment by uzzz** [comment]
leofs supports v2 only

**Comment by delgod** [comment]
Google Cloud Storage supports v2 only
